myapp/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: "posts#index "
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp/app/models/post.rb
class Post < ApplicationRecord
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

myapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/posts_helper.rb
module PostsHelper
end

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar bg-danger">
        <div class="container-fluid">
          <h2 href='#' class='text-warning text-center'>Blogger</h2>
        </div>
      </div>
    </div>
    <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

myapp/app/views/posts/_form.html.erb
<%= form_for(@post,html: { class: "form-vertical" }) do |f| %>

  <fieldset>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="controllar-group">
    <%= f.label :title ,class: 'col-md-12 '%>
    <%= f.text_field :title ,class: 'col-md-12'%>
  </div>

  <div class="controllar-group">
    <%= f.label :body ,class: 'col-md-12'%>
    <%= f.text_area :body ,class: 'col-md-12 row2'%>
  </div>

  <div class="form-actions clearfix">
    <span3 class="pull-right">
      <%= link_to 'Back' , posts_path , class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-primary' %>
    </span3>
  </div>
</fieldset>
<% end %>

myapp/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

myapp/app/views/posts/index.html.erb
<h3>Listing Posts<a href='/posts/new' class="btn btn-large btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i>  New Post</a></h3>

  <ul class="main-list well">
    <% @posts.each do |post| %>
      <li class="row">
        <span class="span6"><%= post.title %></span>
        <div class="pull-right">
          <a href= "<%=post_path(post)%>" class="btn btn-mini"><i class="glyphicon glyphicon-search"></i></a>
          <a href= "<%=edit_post_path(post)%>" class="btn btn-mini"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href= "<%=post_path(post)%>" class="btn btn-danger btn-mini" data-confirm = "Are you sure ?" data-method = "delete" rel = "nofollow"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
      </li>
    <% end %>

  </ul>

myapp/app/views/posts/new.html.erb
<%= render 'form', post: @post %>

myapp/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>